### ISSUE TITLE
1 AI spawns when game is set to no AI

### ISSUE THREAD

**Issue by Todd123178** [justemutarkov/Client#1]
entered a game in factory and set the mode to no ai. but while running around I found a spawned AI, he was immobile as he spawned with no gun, which I also have seen a few times. bots spawning without guns and do not move. have attached screenshot of bot and also the log.
see closed server issue #366 for images.  unfortunately i just printscr and pasted so i did not save them to my local.  will play later and take some screen shots of the bots i have seen without guns floating in mid air

**Comment by InNoHurryToCode** [comment]
@Todd123178
- what is your server and game vesion?
- are mods installed? if so, which ones?
- how can you consistently replicate the issue?

**Comment by Todd123178** [comment]
I'm actually in the dominican republic.  So dont have my pc.  I'll remote
in and let you know.
