### ISSUE TITLE
[Launcher]  Adding new server from lan Network IP doesn't work.

### ISSUE THREAD

**Issue by Tyranidex** [justemutarkov/Client#12]
Connecting to LAN was working on previous version (because we had to enter manually the ip).
Now, it doesn't seems to work on the new Launcher.

**Comment by InNoHurryToCode** [comment]
Can you explain how we can reproduce the issue?

**Comment by Tyranidex** [comment]
My bad, port was not open on the laptop used as a server.
Quick guide to make it working :
 - Open TCP/UDP 666 port in your router settings for your server machine (ex:192.168.1.10).
 - Change ip and port in user/configs/server.json and db/globals.json (ex: 192.168.1.10 and 666)
 - Launch server
 - Launch Client Launcher
 - When adding new server, don't forget to put the port (ex: https://192.168.1.10:666)
 - You can connect on the server

Performance on client seems to be a bit better but not so much.

You can close it.

Take care man
